# Image for individual shopware-setup
# Tag: latest
# Copyright 2024 planlos.xyz
#
# Release: 02.04.2024 / 02:30 pm
FROM php:8.3.4-apache-bookworm
LABEL title="Shopware 6 prod:6.6.0.1" \
    version="8.3.4-apache-bookworm" \
    maintainer="planlos.xyz"

## ***********************************************************************
##  BASE REQUIREMENTS
## ***********************************************************************
RUN ln -fs /usr/share/zoneinfo/Europe/Berlin /etc/localtime \
    && apt-get install -y tzdata \
    && dpkg-reconfigure --frontend noninteractive tzdata

RUN apt update && apt upgrade -y
RUN apt update \
    && apt install -y sudo \
    && apt install -y wget \
    && apt install -y curl \
    && apt install -y unzip \
    && apt install -y bzip2 \
    && apt install -y ssmtp \
    && apt install -y lsof \
    && apt install -y nano \
    && apt install -y zlib1g-dev \
    && apt install -y libicu-dev \
    && apt install -y libzip-dev \
    && apt install -y icu-devtools \
    && apt install -y zip \
    && apt install -y libpng-dev \
    && apt install -y libjpeg-dev \
    && apt install -y libfreetype6-dev \
    && apt install -y curl \
    && apt install -y libcurl4-openssl-dev \
    && apt install -y openssl \
    && apt install -y libsodium-dev \
    && apt install -y git \
    && apt install -y libxml2-dev


## ***********************************************************************
##  APP SERVER REQUIREMENTS
## ***********************************************************************
RUN docker-php-ext-configure gd --with-jpeg=/usr/include/ --with-freetype=/usr/include/
RUN docker-php-ext-install gd && docker-php-ext-enable gd
RUN docker-php-ext-install dom && docker-php-ext-enable dom
RUN docker-php-ext-install ctype && docker-php-ext-enable ctype
RUN docker-php-ext-install iconv && docker-php-ext-enable iconv
RUN docker-php-ext-install curl && docker-php-ext-enable curl
RUN docker-php-ext-install fileinfo && docker-php-ext-enable fileinfo
RUN docker-php-ext-install pdo_mysql && docker-php-ext-enable pdo_mysql
RUN docker-php-ext-install session && docker-php-ext-enable session
RUN docker-php-ext-install simplexml && docker-php-ext-enable simplexml
RUN docker-php-ext-install xml && docker-php-ext-enable xml
RUN docker-php-ext-install opcache && docker-php-ext-enable opcache
RUN docker-php-ext-install sodium && docker-php-ext-enable sodium
RUN docker-php-ext-install intl && docker-php-ext-enable intl
RUN docker-php-ext-install zip && docker-php-ext-enable zip
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli

# set up php-redis-extension
RUN pecl install -o -f redis &&  rm -rf /tmp/pear &&  docker-php-ext-enable redis
RUN docker-php-ext-install  soap && docker-php-ext-enable soap

# activate apache mods
RUN a2enmod ssl rewrite headers proxy proxy_balancer proxy_http

# disable all sites
RUN a2dissite *

# copy needed configurations
COPY ./assets/ports.conf /etc/apache2
COPY ./assets/app.conf /etc/apache2/sites-available
COPY ./assets/install.conf /etc/apache2/sites-available

##
RUN chmod -R 7777 /var/www/html && chown -R www-data:www-data /var/www/html
RUN cd /var/www/html
RUN apt install -y wget
RUN wget https://github.com/shopware/web-recovery/releases/latest/download/shopware-installer.phar.php

RUN a2ensite install

