# Image for individual shopware-setup
# Tag: latest
# Copyright 2024 planlos.xyz
#
# Release: 04.04.2024 / 10:05 am

FROM redis:7.2.4-alpine
LABEL title="Redis Shopware:latest" \
      version="7.2.4-alpine" \
      maintainer="planlos.xyz"

#COPY ./assets/redis.conf /usr/local/etc/redis/redis.conf
#CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
CMD [ "redis-server"]

# Only if the redis server is behind a firewall and has an auth.
EXPOSE 6379
