# Image for individual shopware-setup
# Tag: 7.2.4-alpine
# Copyright 2024 planlos.xyz
#
# Release: 03.04.2024 / 08:20 am

FROM redis:7.2.4-alpine
LABEL title="Redis Shopware:7.2.4-alpine" \
      version="7.2.4-apline" \
      maintainer="planlos.xyz"

#COPY ./assets/redis.conf /usr/local/etc/redis/redis.conf
#CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
CMD [ "redis-server"]