# Image for individual shopware-setup
# Tag: latest
# Copyright 2024 planlos.xyz
#
# Release: 04.04.2024 / 09:55 pm
FROM varnish:7.5.0-alpine
LABEL title="Varnish Shopware:latest" \
      version="7.5.0-alpine" \
      maintainer="planlos.xyz"


COPY ./assets/default.vcl /etc/varnish/

#Port for http
EXPOSE 80